# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Stats on Sight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stats on Sight

  pod 'NVActivityIndicatorView'

  target 'Stats on SightUITests' do
    # Pods for testing
  end

end
